namespace Domain.ColetasOnline;

public record SolicitaCTRRequest(int iCodCidade,
                        int iTipoVeiculo,
                        int iClassificacao,
                        int iClasse,
                        double ivolume,
                        int iGGTipo,
                        string GG_CPF,
                        string GG_Nome,
                        string GG_Email,
                        string GG_Endereco_CEP,
                        string GG_Endereco_Rua,
                        string GG_Endereco_Num,
                        string GG_Endereco_Compl,
                        string GG_Endereco_Bairro,
                        string GG_Endereco_Cidade,
                        string CTR_CEP,
                        string CTR_Rua,
                        string CTR_Num,
                        string CTR_Compl,
                        string CTR_Bairro,
                        string CTR_Cidade,
                        int CTR_Id,
                        int PedidoId);
